In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import models
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
train_data_gen = ImageDataGenerator(rescale=1.0/255,validation_split=0.2)

In [3]:
training_Data = train_data_gen.flow_from_directory(
    "/content/drive/MyDrive/archiveofflower/flowers/flowers",
    target_size=(180,180), 
    batch_size=20,
    shuffle=False,
     subset="training",
    class_mode='categorical'
)
validation_Data = train_data_gen.flow_from_directory(
    "/content/drive/MyDrive/archiveofflower/flowers/flowers",
    target_size=(180,180),
    batch_size=20,
    shuffle=False,
    class_mode='categorical',
     subset='validation'
)



Found 3462 images belonging to 5 classes.
Found 861 images belonging to 5 classes.


In [ ]:
training_Data.class_indices

{'daisy': 0, 'dandelion': 1, 'rose': 2, 'sunflower': 3, 'tulip': 4}

In [4]:
import numpy as np
import os
import PIL
import PIL.Image
import tensorflow as tf
import tensorflow_datasets as tfds

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import RMSprop

In [11]:

model = models.Sequential()

model.add(Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(46, activation='relu'))
model.add(Dense(5, activation='softmax'))

In [13]:
model.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [15]:
# model.fit(
#     training_Data,
#     batch_size=10,
#     epochs = 20)

model.fit(
    training_Data,
    steps_per_epoch = 20,
    validation_data = validation_Data, 
    validation_steps = 20,
    epochs = 200)

#model.fit(training_Data,batch_size=100,epochs=70)

Epoch 1/200
20/20 [==============================] - 190s 10s/step - loss: 38.2129 - accuracy: 0.2475 - val_loss: 13.6920 - val_accuracy: 0.0125
Epoch 2/200
20/20 [==============================] - 75s 4s/step - loss: 17.5129 - accuracy: 0.2750 - val_loss: 6.5874 - val_accuracy: 0.5250
Epoch 3/200
20/20 [==============================] - 61s 3s/step - loss: 17.4249 - accuracy: 0.0675 - val_loss: 15.8036 - val_accuracy: 0.1100
Epoch 4/200
20/20 [==============================] - 55s 3s/step - loss: 13.2658 - accuracy: 0.1990 - val_loss: 25.1825 - val_accuracy: 0.0950
Epoch 5/200
20/20 [==============================] - 53s 2s/step - loss: 13.7701 - accuracy: 0.1975 - val_loss: 11.4830 - val_accuracy: 0.5250
Epoch 6/200
20/20 [==============================] - 58s 3s/step - loss: 13.3156 - accuracy: 0.2125 - val_loss: 3.0005 - val_accuracy: 0.5300
Epoch 7/200
20/20 [==============================] - 38s 2s/step - loss: 9.9773 - accuracy: 0.3325 - val_loss: 23.1576 - val_accuracy: 0.0425


In [16]:
Y = model.predict(validation_Data)
Y

array([[0.06396758, 0.28166777, 0.09687719, 0.30413193, 0.25335562],
       [0.13609818, 0.21232423, 0.14435028, 0.23810579, 0.26912153],
       [0.15228616, 0.20843257, 0.16946109, 0.19717062, 0.27264956],
       ...,
       [0.16208746, 0.2160974 , 0.1732124 , 0.19690016, 0.2517025 ],
       [0.21696241, 0.47454023, 0.14499447, 0.00499005, 0.15851283],
       [0.21866037, 0.43699703, 0.15704042, 0.00942433, 0.17787783]],
      dtype=float32)

In [17]:
predict_class = np.argmax(Y, axis=1)
#predict_class = predict_class.tolist()
predict_class[0:800]

array([3, 4, 4, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 4, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4,
       4, 1, 1, 1, 1, 2, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 4, 4, 4, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 1, 1, 4, 1, 1,
       1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 4, 1, 1, 1, 1, 4, 1,
       1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4, 1, 1, 1, 1, 1, 1,
       4, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 4, 1, 1, 4, 1, 4, 1, 1, 1,
       1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1,

In [18]:
validation_Data.labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,